name: todoliteup
description: A new todo project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  hive: ^2.2.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  dartz: ^0.10.0
  path_provider: ^2.1.2
  kovidoverlook:
    git:
      url: git@github.com:Kianto/KovidOverlook.git
      ref: v0.0.1

  get: ^4.6.6

  cupertino_icons: ^1.0.0
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  hive_test: ^1.0.1
  flutter_lints: ^3.0.2
  network_image_mock: ^2.1.0

  # dart run build_runner build
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
