version: 2
enable-beta-ecosystems: true

registries:
  github-internal:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_PASSWORD}}

updates:
  # Apps
  - package-ecosystem: "pub"
    directory: "/todolite"
    schedule:
      interval: "daily"
      time: "12:15"
      timezone: "Asia/Ho_Chi_Minh"
    registries:
      - github-internal
    open-pull-requests-limit: 2
    labels:
      - "todolite"

  - package-ecosystem: "pub"
    directory: "/todolite"
    schedule:
      interval: "daily"
      time: "12:15"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 2
    labels:
      - "todolite"

  - package-ecosystem: "pub"
    directory: "/todoliteup_1"
    schedule:
      interval: "daily"
      time: "12:15"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 2
    labels:
      - "todoliteup_1"

  - package-ecosystem: "pub"
    directory: "/todoliteup_2"
    schedule:
      interval: "daily"
      time: "12:15"
      timezone: "Asia/Ho_Chi_Minh"
    registries:
      - github-internal
    open-pull-requests-limit: 2
    labels:
      - "todoliteup_2"
