name: 'cache yarn'
description: 'cache yarn'
runs:
  using: "composite"
  steps:
    - name: Use yarn cache
      id: cache-yarn
      uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('flutter/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
