name: 'cache codecov'
description: 'cache codecov'
runs:
  using: "composite"
  steps:
    - name: Add tools path
      shell: bash
      run: |
        mkdir -p "~/.local/bin"
        echo "~/.local/bin" >> $GITHUB_PATH

    - name: Cache codecov
      id: codecov-cache
      uses: actions/cache@v3
      with:
        path: ~/.local/bin/codecov
        key: codecov-${{ runner.os }}-${{ runner.arch }}-1
        restore-keys: |
          codecov-${{ runner.os }}-
