name: 'cache codecov'
description: 'cache codecov'
runs:
  using: "composite"
  steps:

#    - name: Install codecov
#      if: steps.codecov-cache.outputs.cache-hit != 'true'
#      shell: bash
#      run: |
#        curl -s https://uploader.codecov.io/latest/linux/codecov
#
#    - name: Add tools path
#      shell: bash
#      run: |
#        chmod +x codecov
#        mkdir -p "~/.local/bin"
#        cp codecov "~/.local/bin/codecov"
#        echo "~/.local/bin" >> $GITHUB_PATH
#
#    - name: Cache codecov
#      id: codecov-cache
#      uses: actions/cache@v3
#      with:
#        path: ~/.local/bin/codecov
#        key: codecov-${{ runner.os }}-${{ runner.arch }}-1

    - name: Add tools path
      shell: bash
      run: |
        mkdir -p "~/.local/bin"
        echo "~/.local/bin" >> $GITHUB_PATH

    - name: Cache codecov
      id: codecov-cache
      uses: actions/cache@v3
      with:
        path: ~/.local/bin/codecov
        key: codecov-${{ runner.os }}-${{ runner.arch }}-1

    - name: Install codecov
      if: steps.codecov-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        cp codecov "~/.local/bin/codecov"
        chmod +x ~/.local/bin/codecov
