name: 'cache codecov'
description: 'cache codecov'
runs:
  using: "composite"
  steps:
    - name: Cache codecov
      id: codecov-cache
      uses: actions/cache@v3
      with:
        path: codecov
        key: ${{ runner.os }}-codecov-${{ runner.arch }}-1
