name: 'cache codecov'
description: 'cache codecov'
runs:
  using: "composite"
  steps:
    - name: Add tools path
      shell: bash
      run: |
        mkdir -p "~/.local/bin"
        echo "~/.local/bin" >> $GITHUB_PATH

    - name: Cache codecov
      id: codecov-cache
      uses: actions/cache@v3
      with:
        path: ~/.local/bin/codecov
        key: codecov-${{ runner.os }}-${{ runner.arch }}-1

    - name: Install codecov
      if: steps.codecov-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov --output ~/.local/bin
        chmod +x ~/.local/bin/codecov
