name: 'cache codecov'
description: 'cache codecov'
runs:
  using: "composite"
  steps:

    - name: Install codecov
      if: steps.codecov-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -s https://uploader.codecov.io/latest/linux/codecov

    - name: Add tools path
      shell: bash
      run: |
        chmod +x codecov
        mkdir -p "~/.local/bin"
        cp codecov "~/.local/bin/codecov"
        echo "~/.local/bin" >> $GITHUB_PATH

    - name: Cached codecov uploader
      id: codecov-cache
      uses: actions/cache@v3
      with:
        path: codecov
        key: ${{ runner.os }}-codeconv-${{ env.CODECOV_REV }}
