name: 'flutter environment'
description: 'flutter environment'
runs:
  using: 'composite'
  steps:
    - name: Setup flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
