name: 'flutter environment'
description: 'flutter environment'
runs:
  using: 'composite'
  steps:
    - name: Set flutter version
      shell: bash
      run: |
        yarn nx affected --target=fixFlutterVersion
    - name: Set default flutter version
      shell: bash
      run: |
        echo "FLUTTER_VERSION _____ ${FLUTTER_VERSION}."
        echo "FLUTTER_VERSION _____ ${{ env.FLUTTER_VERSION }}."
        if [[ -z "${FLUTTER_VERSION}" ]]; then
          echo "FLUTTER_VERSION=3.16.0" >> $GITHUB_ENV
        fi
    - name: Setup flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
