name: 'flutter environment'
description: 'flutter environment'
runs:
  using: 'composite'
  steps:
    - name: Set flutter version
      shell: bash
      continue-on-error: true
      run: |
        yarn nx fixFlutterVersion ${{ github.event.inputs.target }}
    - name: Set default flutter version if no config
      shell: bash
      run: |
        if [[ -z "${FLUTTER_VERSION}" ]]; then
          echo "FLUTTER_VERSION=3.x" >> $GITHUB_ENV
        fi
    - name: Setup flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
