name: 'flutter environment'
description: 'flutter environment'
runs:
  using: 'composite'
  steps:
    - name: Fix flutter version
      shell: bash
      run: |
        yarn nx affected --target=fixFlutterVersion --base=origin/main --head=HEAD
        if [[ -z "${FLUTTER_VERSION}" ]]; then
          echo "FLUTTER_VERSION=stable" >> $GITHUB_ENV
        else
          echo "FLUTTER_VERSION is already set to ${FLUTTER_VERSION}."
        fi
    - name: Setup flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: $FLUTTER_VERSION
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
