name: 'cache maestro'
description: 'cache maestro'
runs:
  using: "composite"
  steps:
    - name: Cache maestro
      id: cache-maestro
      uses: actions/cache@v3
      with:
        path: ~/.maestro/bin/maestro
        key: ${{ runner.os }}-maestro
