name: Build and upload to Maestro Cloud (Flutter Android)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'todoliteup_2/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install yarn
        run: yarn install

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: todoliteup_2/build/app/outputs/flutter-apk/app-debug.apk
