on:
  pull_request:
    branches: [main]
    paths:
      - 'flutter/apps/edi/**'

jobs:
  dart_code_metrics_analyze:
    name: dart_code_metrics_analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: flutter
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install DCM
        uses: CQLabs/setup-dcm@7092b3baece36963de07d4622312da4e3e9f9b35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yarn
        run: yarn install

      - name: Run dart_code_metrics
        run: |
          yarn nx affected --target=dartCodeMetricsAnalyze --dcmLicenseEmail=${{ secrets.DCM_LICENSE_EMAIL }} --dcmCiKey=${{ secrets.DCM_CI_KEY }}

  dart_code_metrics_check-unused-files:
    name: dart_code_metrics_check-unused-files
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: flutter
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install DCM
        uses: CQLabs/setup-dcm@7092b3baece36963de07d4622312da4e3e9f9b35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yarn
        run: yarn install

      - name: Run dart_code_metrics
        run: |
          yarn nx affected --target=dartCodeMetricsCheckUnusedFiles --dcmLicenseEmail=${{ secrets.DCM_LICENSE_EMAIL }} --dcmCiKey=${{ secrets.DCM_CI_KEY }}
