name: Build and upload to Maestro (iOS)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'todoliteup_2/**'

jobs:
  ios-maestro:
    runs-on: macos-13
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install yarn
        run: yarn install

      - name: Run build debug
        run: |
          yarn nx affected --target=buildDebugIos

      - name: Use maestro cache
        uses: ./.github/actions/cache-maestro

      - name: Install maestro
        shell: bash
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run Upload to Maestro
        env:
          MAESTRO_CLOUD_API_KEY: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
        run: |
          yarn nx affected  --target=maestroIos
