name: Upload to Maestro

on:
  pull_request:
    branches: [main]
    paths:
      - 'todoliteup_2/**'

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - run: todoliteup_2/flutter build apk --debug

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: todoliteup_2/build/app/outputs/flutter-apk/app-debug.apk
