name: pr

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install yarn
        run: yarn install

      - name: Run Analyze & Format
        run: |
          yarn nx affected:lint

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Setup lcov environment
        uses: ./.github/actions/setup-lcov

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: Install yarn
        run: yarn install

      - name: Run Test
        run: |
          yarn nx affected:test

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy-android:
    name: deploy-android
    needs: test
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'edi') &&
      contains(github.event.pull_request.labels.*.name, 'ui/ux')
    defaults:
      run:
        shell: bash
        working-directory: flutter
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: yarn install
        run: yarn install

      - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
        with:
          ruby-version: "2.7"

      - name: Use bundle cache
        uses: actions/cache@v3
        with:
          path: flutter/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('flutter/**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Install Firebase tools
        run: curl -sL firebase.tools | bash

      - name: Deploy App
        env:
          KEYSTORE_PASSWORD: develop
          KEY_ALIAS: develop
          KEY_ALIAS_PASSWORD: develop
          GCLOUD_SERVICE_KEY_DEV: ${{ secrets.GCLOUD_SERVICE_KEY_DEV }}
        run: |
          echo $GCLOUD_SERVICE_KEY_DEV > `pwd`/gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=`pwd`/gcloud-service-key.json
          yarn nx affected --target=deployAndroid --configuration=development --buildNumber=${{ github.run_number }}

  deploy-ios:
    name: deploy-ios
    timeout-minutes: 90
    needs: test
    runs-on: macos-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'edi') &&
      contains(github.event.pull_request.labels.*.name, 'ui/ux')
    defaults:
      run:
        shell: bash
        working-directory: flutter
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: Setup github token
        run: |
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.READONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

      - name: Setup flutter environment
        uses: ./.github/actions/setup-flutter

      - name: Use yarn cache
        uses: ./.github/actions/cache-yarn

      - name: yarn install
        run: yarn install

      - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
        with:
          ruby-version: "2.7"

      - name: Use bundle cache
        uses: actions/cache@v3
        with:
          path: flutter/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('flutter/**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Deploy App
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APPLE_STORE_CONNECT_API_KEY }}
        run: |
          echo $APPLE_STORE_CONNECT_API_KEY_CONTENT > `pwd`/api_key.json
          export APPLE_STORE_CONNECT_API_KEY=`pwd`/api_key.json
          export MATCH_GIT_BASIC_AUTHORIZATION=`echo -n reform-88:${{ secrets.READONLY_GITHUB_TOKEN }} | base64`
          yarn nx affected --target=deployIos --configuration=development --buildNumber=${{ github.run_number }}
